apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "thanos-rule-external-secret"
spec:
  externalSecretName: "thanos-rule-external-secret"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: infra-monitoring
  externalSecretSpec:
    secretStoreRef:
      name: platform-aws
      kind: ClusterSecretStore
    target:
      name: thanos-rule-alertmanager
    data:
      - secretKey: alertmanager-url
        remoteRef:
          key: /infra/thanos-rule-alertmanager
          property: url
